# Generated by Django 2.2.8 on 2020-08-09 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ittamilapp', '0002_auto_20200809_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_on',
        ),
    ]
